### ISSUE TITLE
Copy constructor generation

### ISSUE THREAD

**Issue by danslapman** [ufcpp/RecordConstructorGenerator#2]
Please, add an ability to generate a copy constructor.

**Comment by ufcpp** [comment]
Done.
https://github.com/ufcpp/RecordConstructorGenerator/commit/7fa45697db99229c2c649222df64f0afaf6bf4b9

You can use it in v3.2.0.
https://visualstudiogallery.msdn.microsoft.com/941ef3c4-a523-4d77-8bcd-fdfeebb15853
https://www.nuget.org/packages/RecordConstructorGenerator/3.2.0

**Comment by danslapman** [comment]
It's great! Thank You very much!
