### ISSUE TITLE
Escaping keywords in parameter names

### ISSUE THREAD

**Issue by kharai-tor** [ufcpp/RecordConstructorGenerator#4]
Suppose the class definition looks like this:

``` C#
class Alpha
{
    string Class { get; }
}
```

The code fix generates the following:

``` C#
class Alpha
{
    string Class { get; }
    public Alpha(string class)
    {
        Class = class;
    }
}
```

and the parameter name conflicts with the `class` keyword in C#. Instead the code fix should escape the keywords generating `@class` for this particular example.

I can send a pull request fixing this issue if you accept contributions.

**Comment by ufcpp** [comment]
I’ll consider it.

**Comment by ufcpp** [comment]
I'm sorry for the long delay but now your PR has been merged.

https://www.nuget.org/packages/RecordConstructorGenerator/3.3.0
https://visualstudiogallery.msdn.microsoft.com/941ef3c4-a523-4d77-8bcd-fdfeebb15853

**Comment by kharai-tor** [comment]
It's ok. I'm glad you accepted the PR.
