### ISSUE TITLE
VS 2019 Support

### ISSUE THREAD

**Issue by ufcpp** [ufcpp/RecordConstructorGenerator#8]
reported on Visual Studio Marketplace:

> eroshenko on 09-Dec-2019: 
> Can't install it in VS 2019
> It's not possible to install because there is no following links: Microsoft.VisualStudio.Component.CoreEditor
> Microsoft.VisualStudio.Component.Roslyn.Compiler

**Comment by michaelm7456** [comment]
I've raised a Pull Request [here](https://github.com/ufcpp/RecordConstructorGenerator/pull/9) with a change to allow the Extension to work with Visual Studio 2019.

Applied these changes locally on my environment and looks to be working ok with my VS 2019 Community Edition.

Microsoft Visual Studio Community 2019
Version 16.6.5

<img width="326" alt="Record Constructor Generator Install Success" src="https://user-images.githubusercontent.com/20442719/88483503-3d458e00-cf60-11ea-90f0-9268c0a6b167.png">

Hope this helps!

**Comment by ufcpp** [comment]
updated: https://marketplace.visualstudio.com/items?itemName=iwanaga.Recordconstructorgenerator
